services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb_moodle
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - mariadb_data:/var/lib/mysql

  moodle:
    image: moodlehq/moodle-php-apache:8.2
    container_name: moodle_app
    restart: always
    ports:
      - "8080:80"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: admin
      MOODLE_EMAIL: admin@example.com
      MOODLE_DB_HOST: mariadb_moodle
      MOODLE_DB_USER: moodle
      MOODLE_DB_PASSWORD: moodle
      MOODLE_DB_NAME: moodle
      TZ: Europe/Paris   # ou votre fuseau horaire
    depends_on:
      - mariadb

volumes:
  mariadb_data:
